/* ============================================================================
   P04 — THE REARING FACILITY
   GENERATED by harness/build-places.mjs. Do not hand-edit; edit PLACES.

   A slate, 1.8s, before BF-29. It sits on the same frame as the
   sound's change of acoustic block (the-facility), so the picture and the room
   arrive in the new place together.

   It says where you are and nothing else. A place card that editorialises is a
   title card, and this film has six of those.
   ========================================================================= */
import { hold } from "../engine/motion.mjs";
import { NW, NH } from "../assets/set/_stage.mjs";
import { INK, inkLevel } from "../engine/halfworld-engine.mjs";

export const id = "P04";
export const title = "THE REARING FACILITY";
export const place = "the-facility";
export const plan = null;
export const motion = "HOLD";
export const beats = null;
export const seconds = 1.8;
export const loopClosed = false;
export const frames = 22;
export const declaredBreak = null;
export const breakAt = null;
export const subject = "where we are";
export const distance = "WIDE";
export const leftOut = ["everything that is not the name of this place"];

/* Letterspaced, drawn glyph by glyph — canvas has no letter-spacing, and an
   untracked mono heading reads as a filename rather than a slate. */
function track(g, s, y, size, sp) {
  g.font = `700 ${size}px ui-monospace, Menlo, monospace`;
  g.textAlign = "left"; g.textBaseline = "middle";
  const chars = [...s];
  let w = 0; for (const c of chars) w += g.measureText(c).width + sp;
  let x = NW / 2 - (w - sp) / 2;
  for (const c of chars) { g.fillText(c, x, y); x += g.measureText(c).width + sp; }
  return [NW / 2 - (w - sp) / 2, x - sp];
}

export function at(u) { return { u, h: hold(u, { dur: seconds }) }; }

export function draw(g, W, H, s) {
  g.save();
  g.scale(W / NW, H / NH);
  g.fillStyle = INK;
  const [x0, x1] = track(g, "THE REARING FACILITY", NH * 0.455, 44, 11);
  g.strokeStyle = INK; g.lineWidth = 4;
  g.beginPath(); g.moveTo(x0, NH * 0.525); g.lineTo(x1, NH * 0.525); g.stroke();
  g.fillStyle = inkLevel(5);
  track(g, "BEHIND A PAPER WAREHOUSE", NH * 0.585, 30, 7);
  g.restore();
}

export const SCENE_VERSION = "place/1.0.0";
