#!/usr/bin/env node
/* ============================================================================
   build-places.mjs — WHERE WE ARE.

   THE NOTE THIS ANSWERS: "we don't know what's going on a lot of the film."

   The film moves through five places — a Y-maze in an observation box, a
   laboratory, a converted textile mill, a lot behind it, and a rearing facility
   — and NEVER NAMES ONE OF THEM. Not once in forty scenes. Each location is
   established only by whatever its first shot happens to contain, and the first
   shot of the mill is a fire door, which is a door, not a mill.

   The sound layer already knows the film has five places; it has been mixing
   them as five continuous acoustic blocks with cross-fades at the four
   boundaries. The picture has the same structure and never states it. That is
   the whole defect: a viewer is being asked to infer a five-act geography from
   dot patterns.

   So: five cards, 1.8 seconds each, nine seconds in total, at exactly the four
   places the room tone already changes plus the opening. They say where you
   are and what time it is, and nothing else — no atmosphere, no epigraph, no
   second line of commentary. A place card that editorialises is a title card,
   and the film has six of those already.

   ---------------------------------------------------------------------------
   WHY THIS IS NOT AN ADMISSION THAT THE IMAGES FAILED.

   It is the grammar the film is already in. This is an essay film with a card
   vocabulary — a main title, a trial diagram, a substitution, a precedent — and
   in that form a slate is not a crutch, it is the form. The alternative was to
   make forty scenes each individually explain their own geography, which is how
   you get forty scenes that are about establishing rather than about anything.

   Mono, uppercase, 44px and 30px against a ~33px dot floor. No serif; see
   build-credits.mjs for why the case matters more than the size.

     node harness/build-places.mjs            write scenes/P0*.mjs + order
     node harness/build-places.mjs --report   print the slates, write nothing
   ========================================================================= */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const REPORT = process.argv.includes("--report");
const SECONDS = 1.8;

/* `before` is the scene the card precedes; those five ids are exactly the
   starts of the five acoustic blocks in build-master.mjs, so picture and sound
   change place on the same frame. */
const PLACES = [
  { id: "P00", before: "BF-01", name: "THE OBSERVATION BOX",
    sub: "A Y-MAZE. BOTH ARMS BAITED.", plan: "the-maze" },
  { id: "P01", before: "BF-02", name: "THE LABORATORY",
    sub: "TRIAL 6F-19", plan: "the-laboratory" },
  { id: "P02", before: "BF-15", name: "THE MILL",
    sub: "A CONVERTED TEXTILE FLOOR", plan: "the-mill" },
  { id: "P03", before: "BF-26", name: "THE LOT",
    sub: "BEHIND THE MILL", plan: "the-lot" },
  { id: "P04", before: "BF-29", name: "THE REARING FACILITY",
    sub: "BEHIND A PAPER WAREHOUSE", plan: "the-facility" },
];

const mod = (p) => `/* ============================================================================
   ${p.id} — ${p.name}
   GENERATED by harness/build-places.mjs. Do not hand-edit; edit PLACES.

   A slate, ${SECONDS}s, before ${p.before}. It sits on the same frame as the
   sound's change of acoustic block (${p.plan}), so the picture and the room
   arrive in the new place together.

   It says where you are and nothing else. A place card that editorialises is a
   title card, and this film has six of those.
   ========================================================================= */
import { hold } from "../engine/motion.mjs";
import { NW, NH } from "../assets/set/_stage.mjs";
import { INK, inkLevel } from "../engine/halfworld-engine.mjs";

export const id = ${JSON.stringify(p.id)};
export const title = ${JSON.stringify(p.name)};
export const place = ${JSON.stringify(p.plan)};
export const plan = null;
export const motion = "HOLD";
export const beats = null;
export const seconds = ${SECONDS};
export const loopClosed = false;
export const frames = ${Math.round(SECONDS * 12)};
export const declaredBreak = null;
export const breakAt = null;
export const subject = "where we are";
export const distance = "WIDE";
export const leftOut = ["everything that is not the name of this place"];

/* Letterspaced, drawn glyph by glyph — canvas has no letter-spacing, and an
   untracked mono heading reads as a filename rather than a slate. */
function track(g, s, y, size, sp) {
  g.font = \`700 \${size}px ui-monospace, Menlo, monospace\`;
  g.textAlign = "left"; g.textBaseline = "middle";
  const chars = [...s];
  let w = 0; for (const c of chars) w += g.measureText(c).width + sp;
  let x = NW / 2 - (w - sp) / 2;
  for (const c of chars) { g.fillText(c, x, y); x += g.measureText(c).width + sp; }
  return [NW / 2 - (w - sp) / 2, x - sp];
}

export function at(u) { return { u, h: hold(u, { dur: seconds }) }; }

export function draw(g, W, H, s) {
  g.save();
  g.scale(W / NW, H / NH);
  g.fillStyle = INK;
  const [x0, x1] = track(g, ${JSON.stringify(p.name)}, NH * 0.455, 44, 11);
  g.strokeStyle = INK; g.lineWidth = 4;
  g.beginPath(); g.moveTo(x0, NH * 0.525); g.lineTo(x1, NH * 0.525); g.stroke();
  g.fillStyle = inkLevel(5);
  track(g, ${JSON.stringify(p.sub)}, NH * 0.585, 30, 7);
  g.restore();
}

export const SCENE_VERSION = "place/1.0.0";
`;

console.log(`PLACE SLATES — ${PLACES.length} × ${SECONDS}s = ${(PLACES.length * SECONDS).toFixed(1)}s\n`);
for (const p of PLACES) {
  console.log(`  ${p.id}  before ${p.before.padEnd(6)} ${p.name.padEnd(22)} ${p.sub}`);
  if (!REPORT) fs.writeFileSync(path.join(ROOT, "scenes", `${p.id}.mjs`), mod(p));
}
if (REPORT) process.exit(0);

/* Own our own placement, and do not touch anybody else's — the end roll fell
   out of the running order twice because a generator rewrote the whole file. */
const orderPath = path.join(ROOT, "film", "order.json");
const order = JSON.parse(fs.readFileSync(orderPath, "utf8"));
const mine = new Set(PLACES.map((p) => p.id));
order.cards = [
  ...PLACES.map((p) => ({ card: p.id, before: p.before, why: `where we are: ${p.name.toLowerCase()}` })),
  ...order.cards.filter((c) => !mine.has(c.card)),
];
fs.writeFileSync(orderPath, JSON.stringify(order, null, 1));
console.log(`\n  wrote ${PLACES.length} slates and placed them in film/order.json`);
console.log(`  running order is now: ${order.cards.map((c) => c.card).join(" ")}`);
