#!/usr/bin/env node
/* Writes one thin shell per world, and rewrites the film table in README.md
   from the world modules themselves. A shell is a mount call and nothing else:
   every law lives in halfworld.mjs and every choice lives in worlds/NN-slug.mjs,
   so there is never a second place to fix a bug. The table obeys the same rule
   — a running order maintained by hand is wrong the first time a title changes.
   Re-run after adding or renaming a world. */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const files = fs.readdirSync(path.join(HERE, "worlds")).filter(f => /^\d\d-.*\.mjs$/.test(f)).sort();

for (const f of files) {
  const slug = f.replace(/\.mjs$/, "");
  fs.writeFileSync(path.join(HERE, slug + ".html"),
`<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${slug} — a WYGWYL halfworld</title>
<link rel="icon" href="dot.svg">\n<link rel="stylesheet" href="halfworld.css">
<script type="module">
  import { mount } from "./halfworld.mjs";
  import world from "./worlds/${f}";
  mount(world);
</script>
`);
}
console.log("wrote " + files.length + " shells: " + files.map(s => s.slice(0, 2)).join(" "));

/* ---- the running order, read out of the modules -------------------------
   Numbered 00 is a TITLE OPTION, not a poem. They mount and shoot exactly like
   films because that is the cheapest way to build them, but the running order
   is the fourteen poems and the table must not claim seventeen. */
const rows = [];
const mmss = t => `${Math.floor(t / 60)}:${String(Math.round(t % 60)).padStart(2, "0")}`;
let movements = 0, seconds = 0;
for (const f of files.filter(f => !/^(00|zz)-/.test(f))) {
  const w = (await import(pathToFileURL(path.join(HERE, "worlds", f)).href)).default;
  /* A film that declares `window` is stretched by the runtime to fill its own
     passage of the record, so the sum of its written movement lengths is not
     its running time. The table has to report what plays, not what was typed. */
  const raw = w.movements.reduce((a, m) => a + m.seconds, 0) + 5;   // + the title card
  const s = w.window ? w.window[1] - w.window[0] : raw;
  const at = w.window ? `${mmss(w.window[0])}–${mmss(w.window[1])}` : "—";
  movements += w.movements.length;
  seconds += s;
  rows.push(`| **${w.n}** | [${w.title}](${w.slug}.html) | ${w.tagline || ""} | ${w.movements.length} | ${Math.round(s)}s | ${at} |`);
}
const table = [
  "<!-- FILMS:BEGIN — generated by build-shells.mjs, do not edit by hand -->",
  "| | | | mv | | on the record |",
  "|---|---|---|---|---|---|",
  ...rows,
  `| | **${files.filter(f=>!/^(00|zz)-/.test(f)).length} films** | | **${movements}** | **${Math.floor(Math.round(seconds) / 60)}m ${Math.round(seconds) % 60}s** | **+ the title, 59s** |`,
  "<!-- FILMS:END -->",
].join("\n");

const readme = path.join(HERE, "README.md");
const src = fs.readFileSync(readme, "utf8");
const re = /<!-- FILMS:BEGIN[\s\S]*?<!-- FILMS:END -->/;
if (re.test(src)) {
  fs.writeFileSync(readme, src.replace(re, table));
  console.log(`rewrote the film table: ${files.filter(f=>!/^(00|zz)-/.test(f)).length} films · ${movements} movements · ${Math.floor(Math.round(seconds) / 60)}m${Math.round(seconds) % 60}s`);
} else {
  console.log("README has no FILMS:BEGIN/END markers — table not written");
}
